version: '3'
services:
  app:
    build: .
    environment:
      PORT: 8080
      JWT_SECRET: qsldjhfoidhgfpqozygpzgoieygpoqheioughe
    ports:
      - '8080:8080'
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
